### ISSUE TITLE
请教这里caffe的landmark模型

### ISSUE THREAD

**Issue by zhongwenkun886** [liyuming1978/cvsdk_example#1]
您好，请问你这里面的caffe里的landmark模型是出自哪里的？我试过挺不错的，有训练的脚本（solver.prototxt、train_val.prototxt）吗？我想自己训练一个
谢谢。

**Comment by liyuming1978** [comment]
我离职了, 训练脚本都不在了,  出自mobilenet,  你自己用mobilenet 输出136个点  就行.  网上mobilenet训练脚本一大把

**Comment by zhongwenkun886** [comment]
好的，原来这么简单，谢谢

**Comment by liyuming1978** [comment]
@zhongwenkun886 记得数据集增强， 随机人脸框抖动， 加上人脸的旋转+-10度之内的就行

**Comment by liyuming1978** [comment]
@zhongwenkun886  你可以用effecicnet 之类的网络都行，  回归网络就是这么简单粗暴
